baseURL = '/'
languageCode = 'en-us'
title = 'mikechoj.com'
theme = "archie"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=10 # articles per page

[params]
	mode="toggle" # color-mode â†’ light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "innovation in capital markets, asset management, investor relations"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/mikechoj/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4